Vratislav Blažek, Jiří Bažant, Jiří Malásek - Den je krásný

                                    https://youtu.be/3ykseObmWIQ
         Orig: B - Kapo 0
I:
          G/F    F   G/F    F
On:
             G/F     B7     F              G/F     B7     F
      Den je krásný, den je krásný, den je krásný, den je krásný

      A7   D           Hmi    Emi            A7
      Když dva se rádi mají i v lednu je jak v máji
        Emi            A7     D        Hmi      Emi7     A7
      i v lednu je jak v máji s tebou, s tebou, s tebou, s tebou
Ona:
      D      E/D     Emi7   D              E/D     Emi7   D
      Noc je krásná, noc je krásná, noc je krásná, noc je krásná

      F#7  H             G#mi         C#mi       F#
      Když dva jsou jako jeden, v máj promění se leden,
            C#mi       F#    H        G#mi7    Emi7     A7
      v máj promění se leden s tebou, s tebou, s tebou, s tebou.
Oba:
      D       E/D     Emi7    D              E/D         D
      Svět je krásný, svět je krásný, svět je krásný s tebou.

      F#7  H           G#mi   C#mi           F#7
      Když dva se rádi mají i v lednu je jak v máji
        C#mi             F#7  Hmi      G#mi     Emi7     A7
      i v lednu je jak v máji s tebou, s tebou, s tebou, s tebou

      D       E/D     Emi7    D               E/D        D
      Svět je krásný, svět je krásný, svět je krásný s tebou.

I:
    F#7  H           G#mi          C#mi           F#7
    C#mi             F#7           Hmi    G#mi    Emi7     A7
    D       E/D      Emi7    D             E/D     D 

      F#7  H           G#mi   C#mi           F#7
      Když dva se rádi mají i v lednu je jak v máji
        C#mi             F#7  Hmi      G#mi     Emi7     A7
      i v lednu je jak v máji s tebou, s tebou, s tebou, s tebou

D       E/D     Emi7    D              E/D         D  [: E/D  D]
Svět je krásný, svět je krásný, svět je krásný s tebou.
