Blue Effect - Slunečný hrob

https://www.youtube.com/watch?v=ckNMjjxNWGk

Orig: E

   E    F#mi7                       E/G#                     F#mi
      Usínám a chtěl bych se vrátit o nějakej ten rok zpátky
                           E                      F#mi7            E/G#   F#mi
    bejt zase malým klukem kterej si rád hraje  a který je s tebou

I:
    E   F#mi7    E/G#      F#mi        E         F#mi7     E/G#        F#mi
𝅘𝅥𝅮                E  E  _C# E F# E      F#_G# H H H_C# E E  E_F# F#_G#  G#_H  H_C# C#_E

    E      F#mi7   E/G#      F#mi7             E      F#mi7    E/G#      F#mi
1.  Zdá se mi          je to moc let,          já byl kluk,       kterej chtěl
    E     F#mi7    E/G#       F#mi7     E     F#7 G6   F#7   Fmaj
    znáti svět        s tebou jsem si   hrál ...

    E      F#mi7   E/G#          F#mi7      E       F#mi7   E/G#    F#mi
2.  Vrátím se a       chtěl bych rád        být s tebou       zavzpomínat
    E   F#mi7      E/G#    F#mi7  E     E7
    Mám teď           ale  zprávu zlou

R:
    C#mi  D#mi A     G#mi F#mi7    C#mi     D#mi A      G#mi F#mi
        Suchá  hlína ta   dy              nevzklíčí bez vo   dy
    G#mi     F#mi7    G#mi             H     H7
    Já na ni poklekám    vzpomínkou pocta se vzdává

    E      F#mi7   E/G#   F#mi7               E    F#mi7  E/G#       F#mi
3.  Loučím se         a něco však tam         zůstalo       z těch našich dnů
    E      F#mi7   E/G#     F#mi7  E  F#7 G6   F#7   Fmaj
    já teď vím,       věrný zůsta  nu

Solo:
    E         F#mi7  E/G#        F#mi7      E  F#mi7       E/G#        F#mi
𝅘𝅥𝅮   E    H C# H C#   H C# H G#   F# G G#       H C# H G#   F# G# F# G# H_C#
    E                   F#mi7                E/G#          F#mi7         E
𝅘𝅥𝅮   H_C# E F# H_C# E F# H_C# E F# H_C# E F#  E F# G#_H Aum F#um Eum E C# E
                    E7
𝅘𝅥𝅮   E_F# F#_G# G#_H H Hum H

R:
    C#mi  D#mi A     G#mi F#mi7    C#mi     D#mi A      G#mi F#mi
        Suchá  hlína ta   dy              nevzklíčí bez vo   dy
    G#mi     F#mi7    G#mi          H     H7
    Já na ni poklekám vzpomínkou pocta se vzdává

    E      F#mi7   E/G#   F#mi7               E    F#mi7  E/G#       F#mi
3.  Loučím se         a něco však tam         zůstalo       z těch našich dnů
    E      F#mi7   E/G#     F#mi7  E
    já teď vím,       věrný zůsta  nu

O:
   E            F#mi7          E/G#                   F#mi      E
                F#mi7          E/G#                   F#mi
𝅘𝅥𝅮                              E     E      _C#       E     F#    E
   Nemohu spát, probouzím se a zase se nemohu ubránit myšlence vrátit se o nějakej
     E          F#mi7                   E/G#                  F#mi7               E7
𝅘𝅥𝅮    F#_G# H H  H_C#    E    E          E_F#     F#_G#        G#_H    H_C#  C#_E  E
   ten rok zpátky, bejt zase malým klukem, který si rád hraje, který je s tebou.
