Buty - Mám jednu ruku dlouhou
                              https://youtu.be/2OsSbx-of70
Orig: E - Kapo: 2

I:
   H5  A5 A5  G5 G5  A5 H5 D5
[: D  Hmi7     Emi7 D     A5 H5 D5 :]
   Na nananana naaa naaa

D            Hmi   F#mi         Emi7
1. Najdem si místo kde se dobře kouří
D            Hmi    F#mi      Emi7 
   kde horké slunce do nápojů nepíchá
A           /G    D              G      A       /G    A
   kde vítr snáší žmolky ptačích hovínek  okolo nás a říká

A5 H5 D5 D         Hmi     F#mi          Emi7
2.          Můžeme zkoušet co nám nejlíp zachutná
D              Hmi   F#mi         Emi7   /C
   a klidně se dívat jestli někdo nejde
A            /G  D          G     A        Gmaj   A
   někdo kdo ví, že už tady sedíme a řekne nazdar kluci

R:
  [: D     Hmi        Emi7 D  :]
       Mám jednu ruku dlou hou         uaeeee  Maminkooooo

G           Emi    Hmi        Ami7
3. Posaď se k nám, necháme tě vymluvit
G          Emi     Hmi        Ami7   /F
   a vzpomenout si na ty naše úkoly
D              Ami   G         C        D
   tu ruku nám dej a odpočívej v pokoji
E5 D5 D5  C5 C5  D5 E5 G5
          G             Emi    Hmi          Ami
             tam na tom místě, kde se dobře není
R:
    G     Emi7     C6   G
[:4x   Na nananana naaa naaa    :]
[:3x  G     Emi7       C6  G    :]
[:4x    Mám jednu ruku dlouhou  :] 
