Buty - Malinkého ptáčka
                              https://youtu.be/IskGxpeiXvs
Orig: E - Kapo: 2

I:
[: D6  D6  D6  D6   D6   D6   C6  D6   C    D6   C6  D6 :]
   C/D C/D C/D C/D  C/D  C/D  D6  C/D  D/E  C/D  D6  C/6
   D6  D6  D6  D6   D6   D6   C6  D6   C    D6   C6  D6

        D           /A     D      /A  D   /A
1.	Jednou jsem v lese ptáčka zaa bil
        D    Asus4 D  /A  D  /A
	malinkého  ptáčka
        D        /A    D     /A   D  /A
	hajný se za to na mě zloo bil
        D         /A     G  /A
	malinkého ptáčka měl
        /D          /A   D   /A
	když z lesa domů šel
        D           /A    D    Asus4 D   /A   D  /A
	pod kamenem našel malinkého  ptáčka.

I2:   (melody - hajný...)
      D   /A   D  /A   D  /A   D  /A  G  /A
      /D  /A   D  /A   D  /A   D  Asus4  D  /A  D  /A
      C/D   F+  D    D#   D  /A  D  /A  D  /A

        D           /A     D      /A  D   /A
2.	Jednou jsem v lese ptáčka zaa bil
        D    Asus4 D  /A  D  /A
	malinkého  ptáčka
        D        /A    D     /A   D  /A
	hajný se za to na mě zloo bil
        D         /A     G  /A
	malinkého ptáčka měl
        /D          /A   D   /A
        pod kamenem ho našel
        D           /A    D    Asus4 D   /A  D  /A
	našel pod kamenem malinkého  ptáčka
        D           /A    D    Asus4 D   /A  D  /A
	našel pod kamenem malinkého  ptáčka
O: = I:
