Čechomor - Hruška
                https://youtu.be/hHy1Plu8lU8
Orig: D

I:
   [:4x A A7 :]   Ami   Ami   Ami  Ami

   Dsus2
Stojí hruška v širém poli vršek se jí zelená
[:  Dsus2                               :]
Pod ní se pase kůň vraný pase ho má milá

     D            A          D    G    A
Proč má milá dnes pasete z večera do rána 
[:  D     G    A   D     D   A      D :]
Kam můj milý pojedete já pojedu s váma

I:
  [:8x  A  G  G  A  :]

  D         A           D    G     A
O já pojedu daleko přes vody hluboké
[:  D        G     A    D      D     A  D :] 
Kéž bych byl nikdy nepoznal panny černooké

O:
   D                         G    D    G C D
   G    C    D   G     G  D  G
   G    C    D   Emi
   G         D   F#mi  G  (slow)
