Leonard Cohen - Suzanne
                                 https://youtu.be/svitEEpI07E
Orig: E - Kapo: 2

  D
Suzanne takes you down to her place near the river
        Emi
You can hear the boats go by, you can spend the night forever
        D
And you know that she's half-crazy but that's why you want to be there
        F#mi                                G
And she feeds you tea and oranges that come all the way from China
         D                                  Emi
And just when you mean to tell her that you have no love to give her
        D
Then he gets you on her wavelength
                  Emi                               D                      D
          And she lets the river answer that you've always been her lover
R:
        F#mi                             G
And you want to travel with her, and you want to travel blind    And you
D                                Emi                                D
know that she will trust you For you've touched her perfect body with your mind

    D
And Jesus was a sailor when he walked upon the water
       Emi
And he spent a long time watching from his lonely wooden tower
    D
And when he knew for certain only drowning men could see him
        F#mi                           G
He said all men will be sailors then until the sea shall free them
    D                             Emi
But he himself was broken, long before the sky would open
              D                       Emi                             D     D
          Foresaken, almost human, he sank beneath your wisdom like a stone
R:
        F#mi                         G
And you want to travel with him, and you want to travel blind       And you
D                                         Emi                                D  D
think you maybe you'll trust him For he's touched your perfect body with her mind

       D
Now, Suzanne takes your hand and she leads you to the river
      Emi
She's wearing rags and feathers from Salvation Army counters
        D
And the sun pours down like honey on our lady of the harbor
        F#mi                              G
And she shows you where to look among the garbage and the flowers
          D                                Emi
There are heroes in the seaweed, there are children in the morning
         D                                  Emi
They are leaning out for love and they will lean that way forever
                  D
          While Suzanne holds her mirror
R:
        F#mi                             G
And you want to travel with her, and you want to travel blind          And you
D                                     Emi                                D  D
know that you can trust her For she's touched your perfect body with her mind
