Marek Eben - Polštářky tvých tlapek

https://www.youtube.com/watch?v=ijA_pipADxI

Orig: D

I:
   D      G/D    D      G/D
♪  F#   D G A ^D D A vD G F# D 

Natrhousko:
D               G/D           D             G/D    B     D   Cmaj7    D F#mi F G
Polštářky tvých tlapek toužím dneska v noci pod hlavu si dát

Cmaj7         Ami7  Dmi7    G G+    Cmaj7    Ami7  Dmi7       G G+
Vrnět s tebou stoče ný              u rezavý anté  ny
Cmaj7         Ami7  Dmi7    G G+    Emi7      Ami7  Emi7      A7
Drápky nech zataže  ný              na kočičí mazle ní
 
D             G/D           D             G/D   B   D      G/D    D      G/D
A pak s tebou do posledních kapek mléčnou dráhu vylízat
♪                                                   F#   D G A ^D D A vD G F# D
 
Zelenoocka:
D               G/D           D             G/D    B     D   Cmaj7    D F#mi F G
Polštářky tvých tlapek toužím dneska v noci pod hlavu si dát

Cmaj7       Ami7  Dmi7       G G+
Toulat se zahrada ma
Cmaj7           Ami7  Dmi7   G G+
Tam, kde je zeď spada ná
Cmaj7     Ami7  Dmi7         G G+
Otírat se záda  ma
Emi7         Ami7  Emi7      A7
Být ti zcela odda  ná

D             G/D           D             G/D   B   D      G/D    D      G/D
A pak s tebou do posledních kapek mléčnou dráhu vylízat
♪                                                   F#   D G A ^D D A vD G F# D

Oba:
D               G/D           D             G/D    B     D   Cmaj7    D F#mi F G
Polštářky tvých tlapek toužím dneska v noci pod hlavu si dát

Cmaj7        Ami7  Dmi7      G G+
Hrát si jako koťa  ta
Cmaj7         Ami7    Dmi7   G G+
Když je měsíc v klubíčku
Cmaj7        Ami7  Dmi7      G G+
Střecha bude vyhřá tá
Emi7         Ami7  Emi7      A7
Jenom nemrač tlamičku
 
D             G/D           D             G/D   B   D      G/D    D      G/D   D
A pak s tebou do posledních kapek mléčnou dráhu vylízat                  hmmmmmm
♪                                                   F#   D G A ^D D A vD G F# D
