Marek Eben - Polštářky tvých tlapek

https://www.youtube.com/watch?v=ijA_pipADxI

Orig: ????

Intro: D  G/D  D G/D

NATRHOUŠKO:
  D               G/D          D                D     B   D  Cmaj7 D Fismi Dmi7/A G
Polštářky tvých tlapek toužím dneska v noci pod hlavu si dát
 Cmaj7    Ami7   Dmi7  G G+5
Vrnět s tebou stočený
Cmaj7   Ami7  Dmi7  G G+5
U rezavý antény
Cmaj7   Ami7  Dmi7  G G+5
Drápky nech zatažený
Emi7  Ami7   Emi7  A7
Na kočičí mazlení
 
A pak s tebou do posledních kapek mléčnou dráhu vylízat

ZELENOOČKA:

Polštářky tvých tlapek toužím dneska v noci pod hlavu si dát
Toulat se zahradam
Tam, kde je zeď spadaná
Otírat se zádama
Být ti zcela oddaná
A pak s tebou do posledních kapek mléčnou dráhu vylízat

OBA:

Polštářky tvých tlapek toužím dneska v noci pod hlavu si dát
Hrát si jako koťata
Když je měsíc v klubíčku
Střecha bude vyhřátá
Jenom nemrač tlamičku
A pak s tebou do posledních kapek mléčnou dráhu vylízat
