Marek Eben - Tlapky klást potichu

https://www.youtube.com/watch?v=A94-AIM5Ezc
https://www.youtube.com/watch?v=JKxr07P8tsg

Orig: ???

     D     G    D  G
M: Už jsi velice odvážná.. A to je dobře!

     D              G         D             G
M: Tlapky klást potichu K: Tlapky klást potichu
   D    G        Emi      A         Emi        A
M: Zlehýnka... Jsi přece kočičí K: Jsem přece kočičí
   Emi   A   Hmi     E      Hmi  E
M: Slečinka Ocásek netahej po zemi
    H             E       H  A
   Vousky máš od mlíka slepený

   Ráno až vylezeš K: Ráno až vylezu
M: Z pelíšku Blechy si vydrbej K: Blechy si vydrbu
M: Z kožíšku Protože kočičí holčička
Musí být rozkošná šelmička
     D            G        Fismi  H  A
M+K: Musí být rozkošná  Šelmička...

Sólo harmonica


K: Tlapky klást potichu M: Tlapky klást potichu
K: Ležérně... Ty kluku kočičí
   Nežer, mě Takhle se kocourek nechová
   Vypadáš jak balík z venkova

   Ráno až vylezeš  M: Ráno až vylezu
K: Z pelíšku Blechy si vydrbej  M: Blechy si vydrbu
K: Z kožíšku K: Protože kočičí mladý pán
   Musí být šarmantní elegán
K+M: Musí být šarmantní  Elegán...
