Hoboes - Tunel jménem Čas

https://www.youtube.com/watch?v=adX9RpddoaY

Orig: E

  Edim/G#        D#dim/G#        E
  E              Asmi            E7                         A
𝅘𝅥𝅮 H  E  G# H     H  D# G# H      H  D  G# H   C# H  C#  H   A  F# E C± A
  Ami7                        E          Fmaj/E             E
𝅘𝅥𝅮 A  H  A  H     H  H         G#

        E                 Asmi        E7            A
1. Těch strašnejch vlaků, co se ženou kolejí tvejch snů,
        Ami7      E        F#7           H7
   těch asi už se nezbavíš do posledních dnů,
     E               Asmi      E7           A
   a hvězdy žhavejch uhlíků ti nikdy nedaj' spát,
       Ami7       E        Fmaj            E
   tvá dráha míří k tunelu a tunel, ten má hlad.

      E            Asmi      E7           A
2. Už kolikrát ses mašinfíry zkusil na to ptát,
       Ami7        E           F#7       H7
   kdo nechal roky nejhezčí do vozů nakládat,
        E            Asmi       E7                A
   proč vlaky, co si každou noc pod voknem laděj' hlas,
      Ami7      E        Fmaj         E
   spolyká díra kamenná, tunel jménem Čas.
𝅘𝅥𝅮                                     H  E  G# H ...

      E             Asmi         E7            A
3. Co všechno vlaky vodvezly, to jenom pán Bůh ví,
       Ami7         E             F#7        H7
   tvý starý lásky, mladej hlas a slova bláhový,
     E           Asmi      E7          A
   a po kolejích zmizela a padla za ní klec,
      Ami7         E          Fmaj     E
   co bez tebe žít nechtěla a žila nakonec.

     E              Asmi      E7         A
4. A zvonky nočních nádraží a vítr na tratích
     Ami7        E       F#7      H7
   a honky-tonky piána a uplakaný smích
     E          Asmi         E7         A
   a písničky a šťastný míle na tulácký pas
      Ami7         E        Fmaj         E
   už spolkla díra kamenná, tunel jménem Čas.
𝅘𝅥𝅮                                        H  E  G# H ...

       E             Asmi      E7         A
5. Než poslední vlak odjede, a to už bude zlý,
        Ami7        E        F#7           H7
   snad ňákej minér šikovnej ten tunel zavalí
     E            Asmi         E7        A
   a veksl zpátky přehodí v té chvíli akorát,
     Ami7      E         Fmaj       E
   i kapela se probudí a začne zase hrát.

        E           Asmi      E7             A
6. Vlak v nula-nula-dvacetpět bude ten poslední,
         Ami7       E             F#7        H7
   minér svou práci nestačí dřív, než se rozední,
       E               Asmi         E7           A
   ten konec moh' bejt veselej, jen nemít tenhle kaz,
      Ami7        E         Fmaj         E
   tu černou díru kamennou, tunel jménem Čas.
𝅘𝅥𝅮                                        H  E  G# H ...
Fmaj/E             E
