Jablkoň - Hovada boží
                        https://youtu.be/h2yUXD0WP2Y
Orig: A - Kapo: 7

R:
D                        A7             D
Kampak všichni spěcháme, kampak všichni jdem?
G                        D7             G
Kampak všichni spěcháme, kampak všichni jdem? Jdem
C             G       D             G
tam kde svítí hvězda, tam kde svítí hvězda,
G       D     Emi Hmi    Ami7 D7   G
tam kde svítí hvězda nad hypermarketem. Jdem
C             G      D             G      G       D     Emi Hmi    Ami7 D7   G
tam kde svítí hvězda tam kde svítí hvězda tam kde svítí hvězda nad hypermarketem

Emi                                       Hmi
Vlček vůl i telátko, vlček vůl i telátko, kozička a prasátko, kozička a prasátko
Ami                 Hmi                C               D                    G
myška tygřík opička zajíček i slepička koníček a oslík kravička i mopslík A všechna
   D      G       D7         G       G          D      E Hmi   Ami7  D7   G
ta hovada boží si prohlížejí zboží A všechna ta hovada boží si prohlížejí zboží

R:
D                        A7             D
Kampak všichni spěcháme, kampak všichni jdem?
G                        D7             G
Kampak všichni spěcháme, kampak všichni jdem? Jdem
C             G       D             G
tam kde svítí hvězda, tam kde svítí hvězda,
G       D     Emi Hmi    Ami7 D7   G
tam kde svítí hvězda nad hypermarketem. Jdem
C             G      D             G      G       D     Emi Hmi    Ami7 D7   G
tam kde svítí hvězda tam kde svítí hvězda tam kde svítí hvězda nad hypermarketem

Emi                                       Hmi
Pejsek bobr koťátko, pejsek bobr koťátko, žirafa a hříbátko, žirafa a hříbátko,
Ami                Hmi                 C                    D
kapr blecha medvěd už sem dlouho nejed krokodýl a vlaštovka cvrček mamut dešťovka
          G          D      G    D7         G      G   D  E Hmi Ami7 D7 G
        A všechna ta hovada boží množí se a množí.
R:
D                        A7             D
Kampak všichni spěcháme, kampak všichni jdem?
G                        D7             G
Kampak všichni spěcháme, kampak všichni jdem? Jdem
C             G       D             G
tam kde svítí hvězda, tam kde svítí hvězda,
G       D     Emi Hmi    Ami7 D7   G
tam kde svítí hvězda nad hypermarketem. Jdem
C             G      D             G      G       D     Emi Hmi    Ami7 D7   G
tam kde svítí hvězda tam kde svítí hvězda tam kde svítí hvězda nad hypermarketem

Emi                              Hmi
Lachtan havran veverka     ""    mraveneček ještěrka mraveneček ještěrka
Ami               Hmi                 C                D                 G
stonožka a hrošík ztratil se mi košík krtek zubr kanec to je ale tanec A všechna
   D      G        D7       G       G          D      E Hmi    Ami7 D7   G
ta hovada boží teď nakupují zboží A všechna ta hovada boží teď naku pují zboží
