Elephant Revival, Jefferson Airplane - White Rabbit

                              https://youtu.be/MarQVlEAmBA
Orig: A - Kapo: 7

I:
     [:10x    H   C    :]
H                             C
One pill makes you larger and one pill makes you small
        H                                C
and the ones that mother gives you don't do anything at all
       D5    F             G        D
go ask Alice    when she's ten feet tall

       H
And if you go chasing rabbits and
    C
you know you're going to fall
          H                             C
Tell'em a hooka-smoking caterpillar has given you the call
     D      F       G            D
Call Alice     when she was just small

A                                     D
When men on the chessboard get up and tell you where to go
        A
and you just had some kind of mushroom
         D
and your mind is moving slow
       H             
go ask Alice, I think she'll know

H                              C
When logic and proportion have fallen sloppy dead
        H                                  
and the white knight is talking backwards 
        C
and the red queen's off with her head
  D      F          G        D
Remember   what the Dormouse said
A         D     A         D
Feed your head! Feed your head!
