Jaroslav Ježek, Jan Werich, Jiří Voskovec - Život je jen náhoda

https://www.youtube.com/watch?v=pQ7oNQN-nSI

Orig: C - Kapo:5

I:
 [:  G6                Ami7        D#dim  :]
𝅘𝅥𝅮    D  E  D  E  D  E  G  A  G  A  F#\D#
     G6
𝅘𝅥𝅮    D  G E D H A G E D H A G A H D E

   G             B                    G              E
   Proč že se mi každou noc o tom jen zdá, o tom jen zdá,
        A9               G      D7        G  A9  Cmaj D7
   že v mém životě vyšla má tak šťastná a krásná hvěz da,
   G             B                    G              E
   proč že se mi každou noc o tom jen zdá, že ta hvězda
      A9                   G     D7        G Es F G  C#mi7/5b
   mi dá to štěstí, o němž se mi ve dne nezdá,
   Hmi   F#   F#7      Hmi   E7 
   zdání klame, mimoto každý sen,
           D    Fdim  A7    A+     D  D9  D7  D+
   který v noci mí    váme, zažene příští den.

   G            C7      G                       G7
   Život je jen náhoda, jednou jsi dole, jednou nahoře,
   C           Cmi6     Bmi G       Edim   G D+
   život plyne jak voda a   smrt je jako moře,
   G            C7       G                   G7
   každý k moři dopluje, někdo dříve a někdo později,
   C            Cmi6       G     Edim      G G+
   kdo v životě miluje, ať neztrácí   naději.

   Cmaj               G        Cmaj               G
   Až uvidíš v životě zázraky, které jenom láska  umí,
   A7                 A6  A      Dmaj  Edim Fdim D   D+
   zlaté rybky vyletí nad mraky, pak poro   zu   míš,

   G           C         G                    G7
   že je život jak voda, kterou láska ve víno promění,
   C           Cmi6      G      Edim     G
   láska že je náhoda a  bez ní štěstí není,
   Eb G      Edim     G   Gmaj
   a  bez ní štěstí není.
𝅘𝅥𝅮                         D  G E D H A G E D H A G A H D E
