Kamelot - Zrození hvězd
                                          https://youtu.be/jnkpuz73Bl0
           Orig: A - Kapo 5/0B
I:
   D    Gadd2 G D       Gadd2  G Gmaj G

   D                 G                Hmi               A
1. Zrození hvězd čas vykřesá kvapem a můžou mě vézt, až vyryju drápem
         G            Hmi              Asus4  A
   staré medvědice do skály větrů tvůj obličej.

        D             G                   Hmi        /C F#mi
2. Kraj otěhotněl jak prvnička v máji tou padlou tmou   a někde ve stáji
          G             Hmi                    Asus4  A
       se splaší koně a přiklušou blíž, ke mně blíž.     A
R:
   G                             Hmi       A
   březí klisna má oči jako ty a sedlo z něhy,
         G                                Hmi      A
   možná se jí stýská, možná je zraněná a možná je ty,
               G                                   D
       všechno možná, všechno možná bude lepší než dřív.
I:
    Gmaj G  Hmi7    A  Asus2 A
    G   Gmaj G G6   D                     G   Gmaj G G6  Hmi  A   G  A

           D            G              Hmi            F#mi
3. Tahleta létavice mně do uší zpívá píseň panice, co z tváře ti slíbá
        G             Hmi                  Asus4  A
   tvůj vodopád slz a měsíční prach, co ty víš.

        D          G              Hmi            F#mi
4. Kraj Indiánů mě úsvitem vítá a ranní déšť mou rytinu smývá,
           G                Hmi                Asus4  A
       jsi vzdálená víc, co můžu ti říct, můžu říct,      jen to, že
R:
   G                             Hmi       A
   březí klisna má oči jako ty a sedlo z něhy,
         G                                Hmi      A
   možná se jí stýská, možná je zraněná a možná je ty,
               G                                   D
       všechno možná, všechno možná bude lepší než dřív.
I:
       Gmaj G  Hmi7    A  Asus2 A
       G   Gmaj G G6   D                   G   Gmaj G G6  Hmi  A   G  A
R:
     G                             Hmi       A
   A březí klisna má oči jako ty a sedlo z něhy,
         G                                Hmi      A
   možná se jí stýská, možná je zraněná a možná je ty,
           G                                   D
   všechno možná, všechno možná bude lepší než dřív.
