Kainar, Harris, Young, Plihal - Trochu v hlavě mám
                        https://youtu.be/-aa8rS6Im-w
Orig: D

I:

[: /A /H  Emi  Emi A7  /A /H  Emi  Emi A7
    A6  Dmaj       D6  A6 Dmaj        D6   :]
    A7    D6    /C#   /C    H7    Emi7       Gmi  A7
[: /A /H  Emi  Emi A7  /A /H  Emi  Emi A7
    A6  Dmaj       D6  A6 Dmaj        D6   :]

1.
       Emi         A7        Emi       A7
Trochu v hlavě mám    chodím sem a tam
A6  Dmaj    D6 A6 Dmaj    D6
bloudím        courám

2.
       Emi      A7       Emi     A7
Chodím po Zlíně    voním po víně
A6 Dmaj    D6 A6 Dmaj    D6
zpívám        lí ně

R:
     D6       /C#    /C           H7
Pane strážníku    ta trocha povyku
       Emi                   Gmi A7
to nic není   to mívám ve zvyku

3.
          Emi      A7          Emi      A7
Vždyť sám Alláh ví    že život bez láhví
A6 Dmaj    D6 A6 Dmaj    D6
je zlý        prázdný

I: 1. 2. R 3.
