Druhá tráva - Tanečnice

https://www.youtube.com/watch?v=HGypJfEf-8Q

Orig: D

Intro:
      Hmi A G G  D Hmi A G G A
𝅘𝅥𝅮     

D           A          G                            D          G    D
1. Převrhlá židle jako symbol času         v nočním baru a pak holé nic

D                A          G              D           G      D
   jen v rohu si flitry vyčesává z vlasů      poslední z tanečnic


D           A          G                            D          G    D
2. Jsem poslední host s poslední sklenkou v dlani i ten klobouk mám dnes naposled

D                A          G              D           G      D
   dám si ho do týla a koukám na ni jak šminkou obelhává svět

R:
   D A G    D      G   D     G       D A D A   G     D      G D A    G       D
   Josefíno zatanči mi na rozloučenou za tuhle noc nedopitou   a nedokončenou

   Hmi A G G  D Hmi A G G A
   Á-á-áá-á-áá ...


D           A          G                            D          G    D
3. Bere si tašku moje balerína v ní jen klíč a láhev od piva

D                A          G              D           G      D
   porovná židle a pak pozhasíná a potichu se usmívá


D           A          G                            D          G    D
4. Otvírám dveře - brzkým rozedněním se pak rozmařile nechám vést

D                A          G              D           G      D
   toho kdo zvítězí nad pokušením čeká nebe plné jitřních hvězd

R:

D           A          G                            D          G    D
5. Severní vítr metá svoje kouzla na mém vlnolamu v Tortuze

D                A          G              D           G      D
   do mého nitra právě tiše vklouzla jedna polonahá iluze


D           A          G                            D          G    D
6. Kdesi v mé duši tančí tanečnice možná odvážněji než bych chtěl

D                A          G              D           G      D
   odráží od břehů má plachetnice a říkejte mi Izmael

R:
