Šlitr, Suchý, Matuška - Árie Měsíce

                  https://www.youtube.com/watch?v=_iFQHzZEzww
Orig: F - Kapo 5 - Kapo: 3

I: (whistle)
                    D6
   D                                      A7
Plavu si ani nevím jak, vždyť nemám prsa, nemám znak,
A9                     D  Hmi  Emi7    A7
mám jen hlavu plnou ideá  lů   tududududu
  D                                  A7
a mám rád vodu zelenou a pletu si ji s ozvěnou,
                           D   F#dim Fdim Edim  D   /D /E /F#
narážejí obě na stejnou skálu. tudu  dudu dudu  du.

G        D      A6      D   A9
Mám vodu rád    a proto si  duva duvadu
A7      D      A9             A7    D
na její chlad  duva duvadu    tu zvykám,
G        D         A6        D     A9
hraju si s kapry     i s lososy    duva duvadu
  E             A         /A /A /G /G /F# /F# /E
a tykám         štikám.

/E D                                   A7
Ře kni štiko modrošedá, proč mi voda pokoj nedá,
  A              D6
a proč mě láká a proč mě láká.
/A   D                                         A7
Proč šťasten jsem když do ucha mi chladná voda šplouchá
  A       A6 D       A9      D
a cáká,   a  cáká, a cáká, a cáká.

/H /B  A9                D    A7    D   A
aaaaaaaaaa   lala........
D   A7   D   A  A9  A6  D6  A9  D6
lala........
A9          D6            A9            D      A    D6   A9  D
tap tap tap ...           laaaaaaaaaaaaaaaaaaaa
  A          D
a cáká,   a  cáká.
D  /H /A  A+        D   A  D     D6
Tu tu du  tu tu tu  dududu du    aaaaaaaaaaaaa
