Ivan Mládek - Vánoce v Ďáblicích

https://www.youtube.com/watch?v=5Ed_d04Hsro

Kapo 1

I:
Dsus2 D     Emi Emiadd2     A7sus4 A7       D   A7
Hmm ...

Dsus2 D     Emi Emiadd2     A7sus4 A7       D
Hmm ...

I2 (Harmonica):
      Hmi                 F#mi
𝅘𝅥𝅮 F#  H  C# D   H  C#  D  C# D E   C#  D  E

  Gmaj                    A7
𝅘𝅥𝅮 D  E F#   F#   H  H  D  C#

Dsus2 D     Emi Emiadd2     A7sus4 A7       D   A7
Hmm ...


    Dsus2  D                Emi  Emiadd2
Čas vá     noční trávívám v Ďá   blicích

               A7sus4  A7                 D    A7
S mou známou v sou     kromí, svůj bejvák má


   Dsus2 D                    Emi Emiadd2
Já tý    den s ní sdílím stůl svá teční

          A7sus4 A7            D
Vánočních ná     vyků má známá dbá


     Hmi                F#mi
Že v útulném doupátku v přízemí

        Gmaj                  A7
Závazný slib jí dám, já hrůzu mám


    Dsus2 D               Emi  Emiadd2
Čas vá    noční má zrádná ú    skalí

           A7sus4 A7              D   A7
Kéž dál je má     známá jen známá má

I (Harmonica):
      Dsus2 D                Emi Emiadd2           A7sus4 A7                 D       A7
𝅘𝅥𝅮 A   E     D D   C#DC# H F# G   F#      F#  H  D  D      C# C#    C#  H  E  A

      Dsus2 D                Emi Emiadd2           A7sus4 A7                  D
𝅘𝅥𝅮 A   E     D D   C#DC# H F# G   F#      F#  H  D  D      C# C#    C#  H  C#  D

Že v útulném...

Čas vánoční...

I: (Harmonica + Hmm) fade...
