Ivan Mládek - Vánoce v Ďáblicích

https://www.youtube.com/watch?v=5Ed_d04Hsro

Orig: D# - Kapo 1

I:
   Dsus2 D     Emi Emiadd2     A7sus4 A7       D   A7  /A /H /C#
   Hmm ...
   Dsus2 D     Emi Emiadd2     A7sus4 A7       D
   Hmm ...
       Hmi                 F#mi
♪  F#  H  C# D   H  C#  D  C# D E   C#  D  E (Harmonica)
   Gmaj                      A7
♪  D  E F#   F#   ^H  H  vH  A
   Dsus2 D     Emi Emiadd2     A7sus4 A7       D   A7 /A /H /C#
   Hmm ...

       Dsus2  D                Emi  Emiadd2
1. Čas vá     noční trávívám v Ďá   blicích
                  A7sus4  A7                 D    A7 /A /H /C#
   s mou známou v sou     kromí, svůj bejvák má

      Dsus2 D                    Emi Emiadd2
2. Já tý    den s ní sdílím stůl svá teční
             A7sus4 A7            D
   vánočních ná     vyků má známá dbá

R:
        Hmi                F#mi
   Že v útulném doupátku v přízemí
           Gmaj                  A7
   Závazný slib jí dám, já hrůzu mám

       Dsus2 D               Emi  Emiadd2
3. Čas vá    noční má zrádná ú    skalí
              A7sus4 A7              D   A7 /A /H /C#
   Kéž dál je má     známá jen známá má

I2: (Harmonica) 2x
      Dsus2 D                Emi   Emiadd2
♪ A  ^E     D D   C#um H vF# G    ^F# F#      F#   H   vD
     A7sus4 A7              D (A7 /A /H /C#)
♪    D   C# C#    C#  H  E  A

R:

3.

I2: (Harmonica + Hmm) fade...
