Václav Neckář / Leonard Cohen - Suzanne
                                         https://youtu.be/5A6rD2N1-iw
Orig: A - Kapo: 7

     D
1. Suzanne, místo má, je skryté blízko břehů
        Emi
   sedí tam a proud ji zná a ty závidíš tu něhu,
          D
   i když víš, že pouze blázen má dost sil nést vločku sněhu
          F#mi                           G
   a když svírá vítr v dlaních, tak chce dát nebi duhu
        D                      Emi
   a ty neumíš to říci, jak se její lásky zříci,
          D                        Emi
   víc už nemáš a jsi prázdný, ona říká chyť mi mlhu,
            D                         D
   z jejích vláken spleť tu touhu.
R:
        F#mi                         G
   A ty náhle vstaneš v běhu, poznáš svět je ve vás dvou
        D                        Emi                     D      D
   a ty náhle věříš světu, dokud dál tvé tělo plní myslí svou.

       D
2. Pan Ježíš byl jen lodník, mořem šel měl suchou nohu,
          Emi
   pak se dlouho na svět díval ze své věže v divném slohu
         D
   a sám poznal se smutkem, utopeným nepomohu
         F#mi                     G
   řekl: lidé budou mořem plout a myslel tím jen slzy
        D                          Emi
   a on sám to poznal brzy, nechal nám jen pár slov ryzích,
     D                           Emi                            D     D
   nelidským lidstvím zničen, on zved nás přesto všechny kousek výš.
R: 
        F#mi                         G
   A ty náhle vstaneš v běhu, poznáš svět je ve vás dvou
        D                      Emi                    D     D
   a ty náhle věříš sobě dokud on tvé tělo plní myslí svou.
   
       D
3. Teď Suzanne dá ti dlaň, ve své skrýši blízko břehu
         Emi
   právě obléká ji řeka ve svou nekonečnou něhu
         D
   a jak slunce stéká z nebe tisíc velkých kapek medu
        F#mi                    G
   jimi zlátne celý kraj a lodě plují do přístavu,
         D                          Emi
   vidím spoustu lidí tančit, vidím zlaté děti ráje,
           D                         Emi                        D                 D
   jak nám chrání naši lásku, jak ji chrání jednou pro vždy ó Suzanne v tvých očích
R: 
        F#mi                         G
   A ty náhle vstaneš v běhu, poznáš svět je ve vás dvou
        D                          Emi                     D      D
   a ty náhle věříš v lásku, dokud dál tvé tělo plní myslí svou.
