Nezmaři - Pavučina

CD Zvláštní rána

Orig: A - Kapo 4 - Kapo: 7

 D           Emi7       F#mi7     G       F#mi7     G       F#mi7     Emi7
*: Dlouho se zdá, že to bývám jen já, kdo spálil se postý a neví, jak dál,
   F#mi7      Hmi7        E9         A7        D      Emi7 A7  D   Emi7 A7
   a možná se mýlím, když právě v té chvíli si zpívám.

           D                  Emi      A7
1. Splétám dál svoje sítě, uvidíš, polapím tě,
          A9           G                 D#dim A7   E9          A7          D
   klidně braň se, jak chceš, mně stejně neunikneš, dávno už je upředen můj plán.

       D                       Emi       A7
2. Jen já vím, jak to bude, omotám si tě všude,
          A9    G       D#dim  A7         E9      A7             D
   v mých pavučinách tě opustí strach, až zatáhnu síť a budu jen tvá.

R:
   F#         C#7          F#      F#         C#7         F#
   Vystoupíme k nebetyčným výškám, na vrcholu budem spolu stát,
   A           E7           A  F#mi Hmi          E7         A  A+
   uhádneš-li, po čem se mi stýská, zhoupneme se lásce na vlnách.

       D                        Emi         A7
3. Jen já vím, jak ti bude po těle, zkrátka všude,
          A9    G       D#dim  A7         E9      A7             D
   v mých pavučinách tě opustí strach, až zatáhnu síť a budu jen tvá.

I:
   A7 D     /D#  Emi    A7      A9  G  D#dim  A7  E9  A7  D

 D          Emi7  F#mi7     G     F#mi7      G          F#mi7   Emi7
+: Ničíš mé sítě, ničíš můj klid, všechno je jinak, než mělo by být,
   F#mi7           Hmi7       E9         A7          D      Emi7 A7  D   Emi7 A7
   v tvých pevných poutech mě sám klidně houpeš a já zpívám.

      D                         Emi         A7
4. Naučím tě jiným trikům proti tvým stálým zvykům,
       A9        G         D#dim   A7     E9          A7            D
   teď necháš se vést, jak já umím plést, mně se líbí hlaď mě-obrať mě.

R:
   F#         C#7          F#      F#         C#7         F#
   Vystoupíme k nebetyčným výškám, na vrcholu budem spolu stát,
   A           E7           A  F#mi Hmi          E7         A  A+
   uhádneš-li, po čem se mi stýská, zhoupneme se lásce na vlnách.

      D                         Emi         A7
4. Naučím tě jiným trikům proti tvým stálým zvykům,
       A9        G         D#dim   A7     E9          A7            D
   teď necháš se vést, jak já umím plést, mně se líbí hlaď mě-obrať mě.
       A9        G         D#dim   A7     E9          A7            D
   teď necháš se vést, jak já umím plést, mně se líbí hlaď mě-obrať mě.

O:
   A7 D     /D#  Emi    A7      A9  G  D#dim  A7  E9  A7  D
