Bláznivej den - Pepa Štross /  Nezmaři

https://www.youtube.com/watch?v=m3uNH1Tzyk8   (according to CD Zvláštní rána)

Orig: E - Kapo 2

   D                F#mi           D7             G
1. Bláznivej den se batolí z plen, vítr jak fén a pivo jako křen,
        Gmi                   D           H7        E7      A7
   znáš pár pěknejch míst, že bys radostí písk', já blázen.

   D                F#mi           D7                         G
2. Sluneční zář mi rozjasní tvář, ale i šedivej mrak má svoje kouzlo a tak,
       Gmi             D           H7
   dál šlapu světem, a pod námětem všedních dnů
   E7           A7      D             D7
   z maličkostí skládáš prostý štěstí.

R:
   G                     Gmi                    D                       D7
   Pozoruju děti v parku nebo frontu na polárku a ouřady, jak se zvolna budí,
   G             Gmi         D    D7
   to je recept, jak se nuda nudí.
       G                 Gmi                              D           H7
   Pod pavučinou troleje zpívám si jen tak z voleje třeba o ničem ale s chutí
      E7      A7
   já blázen.

I:
   D     F7 F#7 F7 F#7 F7 F#7     D76     G6
   Gmi      Dmaj       H7         E7      D6   E9       A7

   D                      F#mi         D7                    G
3. Jseš bláznivej flink a mák makovej, život je swing - tvůj názor světovej,
      Gmi             D          H7        E7           A7      D            D7
   to nemá vadu, když náladu máš toulavou, z maličkostí skládáš prostý štěstí

R:
   G                     Gmi                    D                       D7
   Pozoruju děti v parku nebo frontu na polárku a ouřady, jak se zvolna budí,
   G             Gmi         D    D7
   to je recept, jak se nuda nudí.
       G                 Gmi                              D           H7
   Pod pavučinou troleje zpívám si jen tak z voleje třeba o ničem ale s chutí
      E7      A7
   já blázen.

   D                F#mi           D7             G
4. Bláznivej den se batolí z plen, vítr jak fén a pivo jako křen,
        Gmi                   D           H7
   znáš pár pěknejch míst, že bys radostí písk',
   E7           A7      D            H7
   z maličkostí skládáš prostý štěstí,
   E7           A7      D            H7
   z maličkostí skládáš prostý štěstí,
   E7           A7      D
   z maličkostí skládáš prostý štěstí.
