Karel Plíhal - Ve skříni
                         https://youtu.be/1hqitRnsoLM
Orig: Eb - Kapo: 1

I:
   D      A      D  G6   A         D     A    D    G6   A D

      D                A                D   G6         A
Kdesi dole v babiččině skříni bydlí beduíni v její skříni
      D                 A                D      G  Emi A  D
Křičí na mě kámo dej mi čouda cígo za velblouda křičí  na mě

R:
          G        D           A  D
   Dlouhý karavany jdou hlavní třídou
          G        D            A
   dlouhý karavany jdou, já jdu s nima
         G            D           A  D
   zapít trable který jsou, který přijdou,
         G            Hmi      A  G
   je to príma chvíli být mezi svýma.

       D                A             D        G6     A
Člověk míní, Pámbu zase mění, beduíni v skříni zabydlení
      D               A                      D     G  Emi A D
karty hrají pijí vodu z misek kdy je Šrámkův Písek vyzví  dají

R:
          G        D           A  D
   Dlouhý karavany jdou hlavní třídou
          G        D            A
   dlouhý karavany jdou, já jdu s nima
         G            D           A  D
   zapít trable který jsou, který přijdou,
         G            Hmi      A  G
   je to príma chvíli být mezi svýma.

I:
   D       A      D  G Emi A     D     A    D   Gmaj Emi A D

   G   D   A D    G   D   A      G   D   A D    G  Gmaj  A G

       D                 A                D   G  Emi  A  D
V šeru skříně tiše dřepí blázen touží po oáze po tvém klíně...
