Radůza - Zahrály housličky

Orig: A - Kapo: 2

Intro:

  Gmaj             Cmaj        Gmaj            Cmaj
𝅘𝅥𝅮 D     E   D  H   D           D    E  D  H    C  H  A

Gmaj               Cmaj
Zahrály housličky, zahrály tence,

Gmaj                   Cmaj
foukám kouř do svíčky, čekám na milence,

Ami7                G#maj
ten někde toulá se, nebo šel domů,

Gmaj              Cmaj            Gmaj         Cmaj
zahrály housličky tence, Bůh ví komu
𝅘𝅥𝅮                                    G  F# D   E    C  H  A
            
Gmaj              Cmaj
Zahrály housličky v protějším domě,

Gmaj                   Cmaj
srkám čaj z přesličky, vždyť hrajou pro mě,

Ami7           G#maj
barokní gavota přes dvůr se nese,

Gmaj               Cmaj          Gmaj             Cmaj
ať tak a nebo tak, lásky nebojme se
𝅘𝅥𝅮                                D     E   D  H   C

  Gmaj            Cmaj
𝅘𝅥𝅮 D     G  F# D   E    C  H  A

Gmaj              Cmaj
Zahrály housličky po sté takt třetí,

Gmaj                Cmaj
jak pára z konvičky do nebe letí,

Ami7           G#maj
Hynku, Viléme, Jarmilo, Jano,

Gmaj                   Cmaj          Gmaj  Cmaj          Gmaj
foukám kouř do svíčky, zkus to na piáno    zkus to na piáno

Cmaj          Gmaj6
zkus to na piáno
