Radůza feat. Zuzana Navarová - Cestou do Jenkovic

https://www.youtube.com/watch?v=ZIcOlITi9zs

Orig: E - Kapo: 2

I:
   Hmiadd4         Asus4             G6                Asus4
   ⎡Tý                       tydydydudý
   ⎣Tududy dydy ty dydydydau            tududy dydy tu týdydu týdam
   Hmiadd4         Asus4             G6                Asus4         D
   ⎡Tý                       tydydydudý
   ⎣Tududy dydy ty dydydydau            tududy dydy tu týdytu týdytu dau

   D                 Hmi       C                      B    C
1.   Můj děda z kola seskočil,   před prázdnou kašnou na náměstí.
   D                   Hmi       C                 B    C
     Na lavičce chleba posvačil,   seřídil hodinky na zápěstí.

R: 2x
       Dsus2         Asus4                Cadd2            G
     A čápi z komína vod cihelny, zobákem klapou, asi jsou nesmrtelný.

   D                     Hmi      C           B           C
2.   Tři kluci v bílejch košilích   dělili se vo poslední spartu,
   D                    Hmi      C                  B       C
     ze zídky do záhonu skočili,   přeběhli ulici a zmizeli v parku.

R:
       Dsus2         Asus4                Cadd2            G
     A čápi z komína vod cihelny, zobákem klapou, asi jsou nesmrtelný.
       Dsus2                Asus4                Cadd2            G
     A čápi *čápi* z komína vod cihelny, zobákem klapou, asi jsou nesmrtelný

I:
   Hmiadd4         Asus4             G6                Asus4
   ⎡Tý                       tydydydudý
   ⎣Tududy dydy ty dydydydau            tududy dydy tu týdydu týdam
   Hmiadd4         Asus4             G6                Asus4         D
   ⎡Tý                       tydydydudý
   ⎣Tududy dydy ty dydydydau            tududy dydy tu týdytu týdytu dau

   D                 Hmi     C              B        C
3.   V oknech svítěj peřiny,   na bílý kafe mlíko se vaří, 
   D                  Hmi        C                  B         C
     teď právě začaly prázdniny,   venku je teplo a všecko se daří.

R: singers alter
       Dsus2         Asus4                Cadd2            G
     A čápi z komína vod cihelny, zobákem klapou, asi jsou nesmrtelný
       Dsus2                Asus4                Cadd2            G
     A čápi *čápi* z komína vod cihelny, zobákem klapou, asi jsou nesmrtelný
[:4x   Dsus2         Asus4                Cadd2            G         :]  D
     A čápi z komína vod cihelny, zobákem klapou, asi jsou nesmrtelný.   Jéé
