Radůza - Jako zazrakem spis

https://www.youtube.com/watch?v=o5bUpsly1Zo

Orig: Ddur - Kapo: 0

Intro:
          D            A          G         A        D         A        D
𝅘𝅥𝅮         A    .H  A   G±   F# E  F#± E  D  A    A   D     D  .E  F# E  D

   D             A           G  A        D           A        G         A
1. Jako zázrakem spíš, a tak ne víš   že zlou prosím sudičku: "Dobře mu věšť!

   D           A       G  A             D         A       D
   Mně přisuď, co jemu slevíš!"       a do zahrad sype se déšť

   Emi                      D                 Emi                D         A
   zvoní o střechy plech co kapka - to tón já hlídám tvůj dech a můj hlídá On

   D             A           G  A        D         A       D
   jako zázrakem spíš, a tak ne víš   že do zahrad sype se déšť

   
   D         A       G  A                  D        A         G        A
2. Tiše spíš a to je zá zrak          dnes poslední sudička - je to ta třetí

   D        A        G  A             D       A      D
   pohlédne za čas a za zrak          a cestu otevře ti

   Emi        D                       Emi                D          A
   já ji nesu krve své tep            dobře mu suď život dlouhý jak step

   D         A       G  A                  D        A      D
   tiše spíš a to je zá zrak          dnes cesta se otevře ti
   
R1:
    G                 D               G                    D
    Už všechny ovečky přeběhly most   dobrou noc dávno dal i liščí chvost

    Emi                   D           Emi                      D      A
    jen já dneska neusnu, ani kdyby   tisíc jich přes most šlo do koliby


   D                A         G  A       D        A       G    A
3. Tak už spíš a já hledám to kouzlo  co poslední sudičku očaruje

   D             A        G    A              D         A     D
   aby ze rtů jí to slovo sklouzlo    jímž dobrým tě podaruje

   Emi                  D                 Emi                 D         A
   jaké chceš jho snese moje šíje     jen ať život jeho nežli můj delší je

   D                A         G  A        D         A     D
   tak už spíš a já hledám to kouzlo  kéž dobrým tě podaruje

R2: 
    G                  D              G                  D
    Spí všechny ovečky na salaši      jen moje bdění nic nezaplaší

    Emi              D                  Emi                D        A
    já dneska neusnu i kdyby snad     i beránci z nebe šli na salaš spát

Intermezzo:
   D            A          G         A        D         A        G         A
𝅘𝅥𝅮  A    .H  A   G±   F# E  F#± E  D  A    A   D     D  .E  F# G  F#± E  D  E

          D            A          G         A        D         A        D
𝅘𝅥𝅮         A    .H  A   G±   F# E  F#± E  D  A    A   D     D  .E  F# E  D

       Emi                  D                 Emi                 D         A
3/1.   jaké chceš jho snese moje šíje    jen ať život jeho nežli můj delší je

       D                A           G         A       D         A        D
       jako zázrakem    spíš, a tak ne        víš  že do zahrad sype se  déšť
𝅘𝅥𝅮           A     H  A  G±   F# E   F#± E  D  A    A  D     D   E  F# E  D
