Petr Skoumal - Starej pán

https://www.youtube.com/watch?v=geTGDK5r46s

Orig: Eb - Kapo: 1

I:
   E7  Gmi  A7  D              F#7            Ami6             H7   Emi
                Gmi6           D     H7       E7               Gmaj F#
                Hmi            F#             Ami6             H7   Emi
                Gmi6           D     H7       E7         G6         D
R0:
   D                 F#7            Ami6                    H7   Emi
   Starej pán sedí a poslouchá jazz a zdá se mu, jako by to bylo dnes,
   Gmi6         D      H7   E7         Gmaj7  F#7
   jako by zase u baru stál a na pódiu Django hrál.

R:
   Hmi               F#7              Ami6                  H7   Emi
   Starej pán sedí a poslouchá jazz a zdá se mu, jako by to bylo dnes,
   Gmi6              D         H7     E7          A7   D
   starej pán sedí a poslouchá jazz a na desce se točí pes.


       F#7                Hmi       F#7                    Hmi
1. Jó, ráno si vzal čistý ponožky a zajel si do Paríže bez doložky,
   F#7                    Hmi       Gmi6                      A7      A+
   jezdilo se z Wilsonova nádraží a neměli jsme v kufru žádný závaží, jé.

R:
   D                 F#7              Ami6                  H7   Emi
   Starej pán sedí a poslouchá jazz a zdá se mu, jako by to bylo dnes,
   Gmi6              D         H7     E7          A7   D
   starej pán sedí a poslouchá jazz a na desce se točí pes.  C'mon Jazz...

Solo:
   D              F#7            Ami6             H7   Emi
   Gmi6           D     H7       E7               Gmaj F#
   Hmi            F#7            Ami6             H7   Emi
   Gmi6           D     H7       E7         A7         D

       F#7                   Hmi         F#7                Hmi
2. Jó, to tenkrát ještě žila naštěstí ta slečna z Fügnerova náměstí,
   F#7                 Hmi        Gmi6                  A7
   v sobotu kupoval jí pralinky a komunisti byli takhle malinký, jé.

R:
   D                 F#7              Ami6                  H7   Emi
   Starej pán sedí a poslouchá jazz a zdá se mu, jako by to bylo dnes,
   Gmi6              D         H7     E7          A7   D
   starej pán sedí a poslouchá jazz a na desce se točí pes.

Solo:
   D              F#7            Ami6             H7   Emi
   Gmi6           D     H7       E7               Gmaj F#
   Hmi            F#7            Ami6             H7   Emi
   Gmi6           D     H7       E7         A7         D

   F#7                Hmi         F#7             Hmi
3. Vlaky byly čistý a dochvilný a názory a strany rozdílný,
         F#7                     Hmi         Gmi6                        A7
   jenže za starejma časy spadla vopona, teď máme mírnej pokrok v mezích zákona, jé.

R2:
   D                  F#7       Ami6                 H7     Emi
   Tak sedí u starýho přístroje a místo whisky láhev Prazdroje,
   Gmi6              D         H7     E7          A7   D  C# D
   starej pán sedí a poslouchá jazz a na desce se točí pes.
