Až vzlétnou ptáci (Luchin)

Original music and Lyrics: Víctor Jara
Czech Lyrics version: Dušan Vančura of Spirituál Kvintet

https://www.youtube.com/watch?v=rvYMunOmiGE

Orig: D

Solo:
       Hmi/E  A  Hmi/E  A  Gmaj  A7  Hsus2/F#  /F#  /F#

   D6           A7     D6   Gmaj         A7     D6     A7
1. Na předměstí stával dům, malý chlapec si tam hrával

   D6              A7    D6   Gmaj          A7    D6
   drak co vzlétal k oblakům, všechna tajná přání znával.

   Gmaj        A7      G      Gmaj         A7     G
   Draci totiž vždycky ví to, co je klukům nejvíc líto

   Gmaj          A7    Hsus2   Hsus2
   když musí jít večer spát


   D6        A7   D6  Gmaj          A7   D6     A7
2. Jako víno dozrává, jako v mořích vlny hasnou

   D6           A7   D6   Gmaj          A7   D6
   vzpomínka mi zůstává   na tu smutnou zemi krásnou

   Gmaj        A7    G     Gmaj       A7   G
   na rybářské staré sítě, na draka a malé dítě,

   Gmaj       A7       Hsus2    Hsus2
   které nemá si s kým hrát.


   D6          A7     D6   Gmaj       A7     D6       A7
3. Na provázku slunce měl, oblohou se za ním vznášel

   D6         A7      D6    Gmaj         A7    D6
   jako vánek šel kam chtěl smutné lampy lidem zhášel,

   Gmaj       A7     G     Gmaj        A7       G
   pohádkovou dýchal vůní, mluvil řečí horských tůní,

   Gmaj           A7     Hsus2   Hsus2
   průzračnou jak dětský smích.

Solo:

   D6         A7    D6   Gmaj     A7     D6       A7
4. Bílý koník běžel dál  osamělou pustou plání,

   D6            A7      D6    Gmaj         A7    D6
   na dlani sníh dětství tál   i když padal bez ustání,

   Gmaj       A7     G       Gmaj           A7    G
   den začíná tichou flétnou chvíli předtím nežli vzlétnou,

   Gmaj        A7    Hsus2              Hsus2
   hejna ptáků ve větvích.
𝅘𝅥𝅮                    F# C# H  F# C# H   F#   G  A  H   A  G

    D6           A7     D6   Gmaj         A7     D6     A7
1'. Na předměstí stával dům, malý Lučín si tam hrával...

Solo:
                                                       Dmaj
