Vlasta Redl - Husličky

https://www.youtube.com/watch?v=ur2iYxMfUwo

Orig: A - Kapo 2

I:
𝅘𝅥𝅮  G  D  D  D  H  D  E  D
                            G6   Gadd4
𝅘𝅥𝅮  G  D  D  C  Hum C  D  E  D
   G6                Gadd4        G6   Gadd4
𝅘𝅥𝅮  Cum   H  A  H  G  A  E         D

   (silent)
1. Čí že ste, husličky, čie, kdo vás tu zanechal
                                                D/E
   Čí že ste, husličky, čie, kdo vás tu zanechal
   Ami7     D9  Gadd2   Cmaj     D   G    C
   na trávě poválané,   na trávě poválané
   Ami7   Emi7 Dsus2   Ami  G6  D
   u paty oře  cha?

   G                  C  G    Ami      Emi D
2. Kdože tu trávu tak zválal, aj modré fia ly
   G                  C  G    Ami      Emi D
   A kdo tu trávu tak zválal, aj modré fia ly
   Ami7       Dsus2  G    Cmaj  Ami       D       G    C
   že ste, husličky, samé,      že ste, husličky, samé
   Ami      Emi  D    Ami  Emi  D
   na světě zostaly?

   G                   C G     Ami      Emi    D
3. A který tu muzikant usnul a co sa mu přišlo zdát,
   G                 C G     Ami      Emi    D
   Který to mládenec usnul a co sa mu přišlo zdát,
   Ami7     Dsus2  G     Cmaj    Ami      D    G     C
   co sa mu enem   zdálo,   bože co sa mu enem zdálo
   Ami        Emi     D      Ami  Emi  D
   že už vjec nechtěl hrát?

Solo:
   G             C G           Ami      Emi    D
   G             C G           Ami      Emi    D
   Ami7     Dsus2  G     C     Ami      D      G     C
   Ami      Emi    D           Ami      Emi    D

   G6                        Ami7     Emi7 Dsus2
4. Zahrajte, husličky, samy, zahrajte zvesela,
   G6                        Ami7     Emi7 Dsus2

   Ami7     Dsus2  G      C   Ami      D    G      C
   až sa tá bude   trápit,    až sa tá bude trápit,
   Ami      Emi   D  /A /A /H
   která ho nechtěla.

Outro:
   Ami       Emi Asus2 G      Asus C   D    Gadd2
𝅘𝅥𝅮  C  Hum A  H G H  C# D C#um H A  G A D F# Gumumumumum
