Vlasta Redl - Až na poslední stránku
                                https://youtu.be/n7C2QCChfGE
Orig: D - Kapo: 7

C        Gadd4    G            Cmi           G
1. Až na poslední stránku chci napsat to slůvko,
         Gadd4     G      D                  Ami7
   co mi svítí jak slunce   do mých mlhavých dní,
         Gadd4    G           D#dim       G
   na tu poslední stránku, co počmárat zbývá,
                   Hmi   Ami     G
   kolem nakreslím kvítí    nebo sníh.

         Gadd4    G            Cmi           G
2. Na té poslední stránce bude jen jedno slůvko,
       Gadd4     G      D          Ami7  Fadd2
   mým nejtěžším písmem    z první A,
             Gadd4      G          Ami75-        G
   nač jinak všechna ta hejna dětí učit psát krásně,
                        Hmi     Ami     G
             kdybych to nezvlád'    ani já.
I:
D9      G      Ami75-   G      Gadd4   G   /H  Ami7  Ami75-
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Gadd4   G      D#dim    G        Hmi   Ami    G
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

   Gadd4  G            Ami75-    G
3. Zvolna chápu, proč slova se píšou,
       Gadd4   G      D              Ami7
   aby bylo co zpívat a aby bylo čím lhát,
D9                     G          D#dim          G
   všechna slova svých písní bych napsal tím slůvkem,
                              Hmi     Ami      G
              tak chápeš, jak spěchám    se ho vzdát
I:
D9      G      Ami75-   G        Gadd4   G   /H  Ami7  
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
D9      G      Cmi      G           Hmi   Ami     G
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

                    Hmi     Ami     G
    tak chápeš, jak spěchám   se ho vzdát
