Vlasta Redl - Letiště
                     https://youtu.be/RSSijUAlwF0
Orig: D - Kapo: 0

I: 4x
   D     G   G D Emi A

   D           G        Ami7    D7    G
1. Koupil jsem za babku letenku do ráje,
   D           G6         Emi       A     D E
   trochu jsem přemýšlel, zda vůbec pravá je,
   D9/F#      D7          G          Ami7  D
   bylo čtvrt na dvanáct, gól přišel právě včas,
   D          G        Ami7     D7     G
   z tlampače nad námi ozval se klidný hlas:
   G C D   C       Ami7 Hmi7  Emi7 D9 D7 G
   letadlo do ráje odlétááááááááááááááááááá

   D           G          Ami     D7    G
2. Dostal jsem instrukce, padák a espresso,
   D        G6      Emi     A   D    E
   hrály se karty a šlo eso na eso,
   D9/F#      D7       G       Ami7  D
   všichni se snažili, aby nám utek' čas,
   D          G        Ami7     D7     G
   z tlampače nad námi ozval se klidný hlas:
             G C D   C       Ami7 Hmi7  Emi7 D9 D7 G
             letadlo do ráje přilétáááááááááááááááááá
I:
G/H /C Dadd4 G6    G/H /C Dadd4 G6      G/H /C /H /C B6 Ami7 G(flag)

   D      G          Ami7       D7       G
3. Už ani nevím sám, jak dlouho jsem tam byl,
        D        G6      Emi    A       D   E
   a je marné to líčit - stejně bys nevěřil,
   D9/F#     D7        G         Ami7   D
   ráno jsme zaspali a na nic už nezbyl čas,
   D   Dsus4  D Dsus2   G
   ahoj - ahoj, a někdy zas,
   G C D   C      Ami7 Hmi7  Emi7 D9 D7 G
   letadlo z ráje odlétááááááááááááááááááá

   D      G        Ami7      D7       G
4. Pomalu stoupáme v kruzích nad letištěm
   D         G6        Emi         A     D    E
   smutným a nevlídným jak prázdné hlediště,
   D9/F#    D7        G          Ami7   D
   dívám se na tebe a přemýšlím, jak je ti,
G/H /C Dadd4 G6    G/H /C Dadd4 G6     G/H /C /H /C B6 Ami7 G(flag)
     letadlo přiletí,      a odletí ...
