Vlasta Redl - Vlaštovka
                          https://youtu.be/hVqP73DQBjI
Orig: G# - Kapo: 6

I:
   [:     D        /C#       /H        /C#      D         /C# /H /C# :] (7.fret)

          D        /C#       /H        /C#      D         /C# /H /C#
1. Jednou večer mi do pokoje přiletěla papírová vlaštovka,       to mám
   D                 /C#                 /H            /C#                D     /C# /H
   z toho, že v zimě větrám, tak jsem ji zved a dal ji do tepla, zábla ji výškovka,
/C#            Bmaj                 Ami7            Bmaj                   E7sus4
   pak jsem si prohlíd' její křídla jemně, proč asi přilétla, a proč právě ke mně,
          D         /C#    /H         /C#      D      /C# /H
   byla z Ahoj na sobotu a byla na ní otištěná hitovka.

R:
   /A   /H /C#  D                            A         Esus4  F#add4 F#
   Nej  hezčí   dárek nemusí přinést vždycky Děda Mráz,
               Hmi   Hmi7        E                     Aadd4
   vletí k vám oknem něco, co by létat snad raději nemělo,
            Cmaj                             F#add4 F#
   někdo si vzpomněl, říkáte si, někdo na mě myslí,
              Hmi    Aadd4       G       Gadd2
   nebo je to zas          jenom špás,
          D         /C#            /H    /C#            D   /C# /H /C#
   tak či tak, když přiletí vlaštovka,   hned je v domě veselo.

(voice_octave_up) D           /C#      /H           /C#       D        /C# /H /C#
2. Tak jsem si    pomalu slabikoval tu písničku, co přiletěla z éteru,        poslední
   D              /C#             /H           /C#           D       /C# /H /C#
   rok jsem tolik skládal, že moc nechybělo, a složil bych i operu,
             Bmaj                   Ami7      Bmaj               E7sus4
   jen místo múzy mě častěji líbala můra, ono písní se dá složit fůra,
          D          /C#              /H      /C#     D        /C# /H /C#
   ale ne každá může letět, i když se vypustí správně po směru.

             G     Gadd4      G         Gadd4       G         Gadd4  G      Gadd4
*: K čemu to bylo, všechno to skládání, když stejně nikdo nic nepo   chopil
          Emi       Ami7    Emi7      D          G        Gadd4 G
   a moje vlaštovky odlétly na jih, a s těma, co zůstaly, někdo topil,
       Emi7     Ami7     Emi7      D         G         Gadd4     G
   jen jedna se vrátila, a já jsem čekal jak blázen, a věřil, že platí,
      Emi         Ami7       Emi7  D         G      Gadd4  G     D
   že všechno, co necháš, ať letí, jednou se k tobě určitě vrátí,
      Emi7                   C               G      D     Ami7
   že všechno, co necháš, ať letí, jednou se k tobě možná vrátí.

              D                  /C#       /H    /C#         D         /C# /H /C#
3. A tak jsem pálil archív svých písniček,       to se roura styděla,
             D             /C#      /H              /C#          D       /C# /H /C#
   a když mi zbyl poslední papír,   hned jsem věděl     co s ním udělám,
       Bmaj                Ami7          Bmaj                                  E7sus4
   roh na roh - šlo to bez problémů, jen jestli poletí, z toho měl jsem trochu trému,
   D           /C#          /H    /C#          D        /C# /H  /C#
   to ví přece každý, že co letí,    na tom se vydělá.

   D                 /C#        /H        /C#       D     /C# /H /C#
4. Mávl jsem rukou z okna, a ta vlaštovka doopravdy letěla,
          D              /C#            /H      /C#     Dsus2
   i když bralo ji to na stranu, asi ji tížilo, že jaro nedělá ...
