Žalman a spol. - Divoký horský tymián

https://www.youtube.com/watch?v=gWhZOFxfiVc

Orig: D

I:
   Dadd4                    Dadd4 G   Dadd4
𝅘𝅥𝅮  (flute)            D  H  A     H ./D 
         G          Dadd4            G             F#mi7
𝅘𝅥𝅮  F# A  H      A   F#  A      F# A  H    A   F#   E
         Emi           G            Dadd4 G   Dadd4
𝅘𝅥𝅮  E  F# G    F# E  D  H  D   D  H  A     H ./D
 
          D     G     D                  G           D 
1. Dál za vozem spolu šlapem,      někdo rád a někdo zmaten,
          G           F#mi               Emi               G 
   kdo se vrací, není sám,         je to věc, když pro nás voní
           D     G     D 
   z hor divokej   tymián.
 
         D      G      D                  G               D 
2. Léto, zůstaň dlouho s námi,     dlouho hřej a spal nám rány,
         G           F#mi                Emi               G 
   až po okraj naplň džbán,        je to věc, když pro nás voní
           D     G     D     Dsus2  D
   z hor divokej   tymián 
 
R:
       G             D                     G        F#mi 
   Podívej, jak málo stačí,        když do vázy natrhám
         Emi        G                      D     G     D 
   bílou nocí k milování           z hor divokej   tymián.
 
I:
   Dadd4                    Dadd4 G   Dadd4
𝅘𝅥𝅮  (flute)            D  H  A     H ./D 
         G          Dadd4            G             F#mi7
𝅘𝅥𝅮  F# A  H      A   F#  A      F# A  H    A   F#   E
         Emi           G            Dadd4 G   Dadd4
𝅘𝅥𝅮  E  F# G    F# E  D  H  D   D  H  A     H ./D

          D     G       D                G             D
3. Dál za vozem trávou, prachem,   někdy krokem, někdy trapem,
          G          F#mi                Emi               G
   kdo se vrací domů k nám,        je to věc, když pro nás voní
           D     G     D     Dsus2  D
   z hor divokej   tymián.

R:
       G             D                     G        F#mi
   Podívej, jak málo stačí,        když do vázy natrhám
         Emi        G                      D     G     D
   bílou nocí k milování           z hor divokej   tymián.
 
I:
   Dadd4                    Dadd4 G   Dadd4
𝅘𝅥𝅮  (flute)            D  H  A     H ./D 
         G          Dadd4            G             F#mi7
𝅘𝅥𝅮  F# A  H      A   F#  A      F# A  H    A   F#   E
         Emi           G            Dadd4 G   Dadd4
𝅘𝅥𝅮  E  F# G    F# E  D  H  D   D  H  A     H ./D
